parameters:
#    house_finder_parser.example.class: HouseFinder\ParserBundle\Example

services:

#  housefinder.parser.slando:
#    class: HouseFinder\ParserBundle\Service\SlandoService
#    arguments: [@service_container]