parameters:
#    house_finder_parser.example.class: HouseFinder\ParserBundle\Example

services:
#    house_finder_parser.example:
#        class: %house_finder_parser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
