parameters:
#    house_finder_parser.example.class: HouseFinder\ParserBundle\Example

services:


  housefinder.parser.service.slando:
    class: HouseFinder\ParserBundle\Service\SlandoService
    arguments: [@service_container]

  housefinder.parser.parser.slando:
    class: HouseFinder\ParserBundle\Parser\SlandoParser
    arguments: [@service_container, @housefinder.parser.service.slando]
